import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Nabvar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="a">
      <body className={inter.className}>
        <Navbar />
        <div className="flex justify-center items-center">
          {children}
        </div>
        < Footer />
      </body>
    </html>
  );
}
